### ISSUE TITLE
メモを更新したあとメモ新規作成画面に遷移する

### ISSUE THREAD

**Issue by Koresue** [ASO1901029/sk2020_5K#119]
メモを更新したあとメモ新規画面に遷移ではなく、更新されたメモの画面のままの方がいい。確認のためにもう一度更新したメモを探すのも面倒。

**Comment by ASO1901029** [comment]
要話し合い

**Comment by ASO1901029** [comment]
新規作成の場合→もう一度、新規作成画面
更新→同じものの編集画面を続けて表示？（ならそれっぽい内容の通知を出したい）

**Comment by ASO1901029** [comment]
保存しました的な表示のToastを出したい
