### ISSUE TITLE
サインアウトボタンをアカウント画面内に移動させる

### ISSUE THREAD

**Issue by Koresue** [ASO1901029/sk2020_5K#146]

**Comment by ASO1901029** [comment]
Toastは通知用？だから多分入力させるのは違うと思う

**Comment by ASO1901029** [comment]
誤爆対策なら、サインアウトが誤爆しやすい配置（上部）にあるのが主な原因で、それを下の方に移動させるのがいいかもしれない

**Comment by ASO1901029** [comment]
そもそもサインアウトボタン自体をなかなか使わないのでアカウント画面に移動
