### ISSUE TITLE
招待URLを発行できるようにしたい（現状はURLバーからコピペ）

### ISSUE THREAD

**Issue by Koresue** [ASO1901029/sk2020_5K#152]
アイデア手法（ブレスト、マンダ）の招待URL

**Comment by ASO1901029** [comment]
現状の構成だと開始前（設定画面）で招待することはかなり難しいので、開始後の画面（_edit_menu)の各ユーザが表示されているところ）に[SHARE]ボタンを用意するといいかもしれない
