### ISSUE TITLE
マンダラート 編集中にならない時がある

### ISSUE THREAD

**Issue by ASO1701005** [ASO1901029/sk2020_5K#168]
重い
入力すると背景色が灰色（編集中）になるはずが、たまに変わらない。
何かキーを押すと、編集中に変わったりもする。
確定後に編集中に変わったりとよくわからない。

**Comment by ASO1901029** [comment]
要調査。
初回時に走るJSが重い可能性？

**Comment by ASO1701005** [comment]
多少はよくなった気がする？
普通に使う分には問題ないと思う
一旦置いときたいです

**Comment by ASO1901029** [comment]
これって原因は不明？

**Comment by ASO1701005** [comment]
うーん
jsが重いだけのような気がする
