### ISSUE TITLE
ブレインストーミングにて残り時間の表示が行えていない

### ISSUE THREAD

**Issue by CatsManma** [ASO1901029/sk2020_5K#169]

**Comment by ASO1901029** [comment]
作成時の時間と各プロセスの時間から終了する時間を計算して、現在の時間との差を表示すれば良さげ

**Comment by ASO1901029** [comment]
各時間はidea_logではなくideaから取得したほうが綺麗に処理できそう。
というかideaのoptionにちゃんとデータ入れよう・・
