### ISSUE TITLE
アイデアの新規作成画面などで縦幅を小さくすると全体でスクロールできるようになってしまう

### ISSUE THREAD

**Issue by ASO1901029** [ASO1901029/sk2020_5K#249]
アイデアの新規作成画面などで縦幅を小さくするとスクロールできる
left_menuは画面の縦幅に収まるがその外にスクロールできてしまう。
main_contentをスクロール可能にするCSSを書けばはみ出すことはなくなる・・かも？

**Comment by ASO1701005** [comment]
leftメニューをスクロール可能にする事で解決
