### ISSUE TITLE
マンダラート 入力欄上寄せになっている

### ISSUE THREAD

**Issue by ASO1701005** [ASO1901029/sk2020_5K#288]
調べてみた感じtextareaにしたことで上下の中央寄せができないかも

新しくdivを作って空白をつくる？

**Comment by ASO1901029** [comment]
要検討。テキストエリアにする以上入力欄が左上になるのは仕方がない。
対応するなら確定後textareaからdivかなにかに転記して中央寄せになるとかかな(入力欄と表示欄が実は別のモノという感じ)
