### ISSUE TITLE
マンダラートにて残り時間のリアルタイム表示が行えていない

### ISSUE THREAD

**Issue by CatsManma** [ASO1901029/sk2020_5K#391]

**Comment by ASO1901029** [comment]
idea_channel.rbがマンダラートを考慮した形式になっていないことによる不具合（マンダラートにprocess2,3は存在しない）
159行目の`def get_process_time`
183行目の`def subscribed_target_time`
あたりが怪しいと思われる

**Comment by ASO1901029** [comment]
恐らくidea_channel.rbがマンダラートを考慮した形式になっていないことによって途中でエラーが発生し処理が止まることに寄る不具合（マンダラートにprocess2,3は存在しない）
159行目の`def get_process_time`
183行目の`def subscribed_target_time`
あたりが怪しいと思われる
