### ISSUE TITLE
 【ブレインストーミング】履歴から遷移した際にブレインストーミングでEnterが反応しない

### ISSUE THREAD

**Issue by ASO1901029** [ASO1901029/sk2020_5K#52]
履歴から遷移した際、Enterが効かず入力ができない。  
リロードすれば正常に動く。

**Comment by ASO1901029** [comment]
上手くJavaScriptが反応していない？Ajax遷移関連のバグ？（要検証）

**Comment by CatsManma** [comment]
履歴画面で更新をかけた後に発生する模様

**Comment by ASO1801017** [comment]
履歴からブレストを開いた場合アイデア追加することないような・・・？
